name: Paper Summary
title: Paper Summary
url: https://msank00.github.io/papersummary/
baseurl: "https://msank00.github.io/papersummary/"
twitter_username: imridhasankar
github_username:  msank00
linkedin_username: sankarshanmridha
description: Paper Summary
author: Sankarshan Mridha
# email: sanakarshan7@gmail.com
permalink: /blog/:year/:month/:day/:title
theme: minima

# theme: jekyll-theme-minimal

# Conversion
markdown: kramdown

plugins:
  - "disqus-for-jekyll"
  - jekyll-feed
  - jemoji

header_pages:
  #- resume.md
  - blog/index.html
  - index.md
