name: Paper Summary
title: Paper Summary
url: https://msank00.github.io/
baseurl: "/papersummary"
twitter_username: imridhasankar
github_username:  msank00
linkedin_username: sankarshanmridha
description: Paper summary
author: Sankarshan Mridha
# email: sanakarshan7@gmail.com

permalink: /sankarshan/:category/:year/:month/:day/:title

# /:category/:year/:month/:day/:title/
# /blog/:year/:month/:day/:title

# Build Setting
markdown: kramdown
theme: minima

plugins:
  - jekyll-feed
  - jemoji

header_pages:
  - blog/index.html
  - index.md
